version: '3'
services:
    php:
        build:
            context: ./
            dockerfile: php.dockerfile
        volumes:
            - code:/code
        command: sh -c "chmod -R 777 /code/storage; php-fpm"

    nginx:
        image: nginx:1.12-alpine
        volumes:
            - code:/code
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80

    database:
        image: postgres:10-alpine
        environment:
            POSTGRES_DB: dbname
            POSTGRES_USER: example
            POSTGRES_PASSWORD: example
    
    cache:
        image: redis:3-alpine

    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
        environment:
            discovery.type: single-node
        volumes:
            - ./jvm.options:/usr/share/elasticsearch/config/jvm.options

volumes:
    code:
        driver: local
        driver_opts:
            device: $PWD
            o: bind

networks:
    default:
        driver: bridge
